on: 
  push: 
    branches: 
      - master

name: Build and Publish
jobs:
  build:
    name: Build Library
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 10.17
    - uses: actions/cache@v1
      id: cache-modules
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
    - run: npm install
      if: steps.cache-modules.outputs.cache-hit != 'true'
    - run: npm run-script build
    - run: npm run-script test
    - run: npm run-script test:badges
    - name: Upload esm build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-esm
        path: esm
    - name: Upload lib build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-lib
        path: lib

  deploy:
    needs: build
    name: Deploy Library
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 10.17
    - uses: actions/cache@v1
      id: cache-modules
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
    - name: Download build-lib
      uses: actions/download-artifact@v2
      with:
        name: build-lib
        path: lib
    - name: Download build-esm
      uses: actions/download-artifact@v2
      with:
        name: build-esm
        path: esm
    - name: Deploy to NPM! 🚀
      uses: benwinding/merge-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  demo:
    needs: build
    name: Deploy Demo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 10.17
    - uses: actions/cache@v1
      id: cache-modules
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
    - run: npm run-script build-for-demo
    - run: npm run-script build
      working-directory: ./demo
    - name: Deploy 🚀
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: demo/build # The folder the action should deploy.
